### ISSUE TITLE
Proposal: parametric docker-compose file 

### ISSUE THREAD

**Issue by giobart** [edgeIO/src#31]
In order to make easier the automated deployment of the EdgeIO's components it would be nice to have some variables for the compose file of the cluster manager. 

For instance a minimum set of variables that we can set would be something like the following example:

```
  cluster_manager:
     ...
    environment:
      ...
      - SYSTEM_MANAGER_URL=${SYSTEM_MANAGER_URL}
      - CLUSTER_NAME=${CLUSTER_NAME}
      - CLUSTER_LOCATION=${CLUSTER_LOCATION}
```

In this example, by exporting the variables **SYSTEM_MANAGER_URL**, **CLUSTER_NAME** and **CLUSTER_LOCATION** in the target machine, we can directly use the `docker-compose up` command without having to manually modify the docker-compose file to match the root orchestrator. 

This would make the implementation of the automated deployment scripts pretty straight forward.

**Comment by meeeehdiiii** [comment]
yes can work. go for it.
